name: AUM Monitor Bot

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  monitor_aum:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests python-telegram-bot

      - name: Run AUM monitor script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python monitor_aum_bot.py
