name: Discord Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # Runs the bot every 10 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install discord.js

      - name: Run bot
        run: node bot.js
